[package]
name = "corduit-crypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Dependency-free, no_std cryptographic primitives for Corduit"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["alloc"]
alloc = []
test-vectors = []

[dependencies]

[dev-dependencies]
