[package]
name = "corduit-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Protocol implementations for Corduit"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["quic", "tls", "wireguard", "tuic", "tuic-quinn"]
quic = []
tls = []
wireguard = []
tuic = []
tuic-quinn = []

[dependencies]
bytes = { workspace = true }
corduit-crypto = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
getrandom = { workspace = true }
h2 = { workspace = true }
http = { workspace = true }
nextjson = { workspace = true }
parking_lot = { workspace = true }
pin-project-lite = { workspace = true }
quinn = { workspace = true }
rustls = { workspace = true }
rustls-native-certs = { workspace = true }
rustls-pki-types = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tokio-tungstenite = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
tokio-test = { workspace = true }
