[package]
name = "corduit-dns"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "DNS resolver and server for Corduit with anti-spoofing, caching and fake-IP support"

[package.metadata.docs.rs]
all-features = true

[dependencies]
bytes = { workspace = true }
corduit-common = { workspace = true }
corduit-crypto = { workspace = true }
dashmap = { workspace = true }
getrandom = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
ipnet = { workspace = true }
nextjson = { workspace = true }
parking_lot = { workspace = true }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tracing = { workspace = true }
webpki-roots = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
tokio-test = { workspace = true }
tracing-subscriber = { workspace = true }
