[package]
name = "corduit-netstack"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version = "1.85"
readme.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Userspace TCP/IP stack and TUN device management for transparent proxying"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["ipv4", "ipv6", "tcp", "udp", "icmp", "dns"]
embed-wintun = []
dns = []
icmp = []
ipv4 = []
ipv6 = []
tcp = []
udp = []

[dependencies]
bytes = { workspace = true }
corduit-dns = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
lru = { workspace = true }
nextjson = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
pin-project-lite = { workspace = true }
rand = { workspace = true }
smoltcp = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }
tun-rs = { workspace = true }

[target.'cfg(windows)'.dependencies]
corduit-common = { workspace = true }
wintun-bindings = { workspace = true }
zip = { workspace = true }
