//! Argon2id (RFC 9106 §5.3) — the memory-hard KDF Snell v4/v5 derives its
//! AEAD key with.
//!
//! Only the **id** variant is implemented, because only the id variant is
//! needed: `argon2.IDKey(psk, salt, 3, 8, 1, 32)` in the Snell reference is
//! Argon2id with three passes, an 8 KiB memory cost, one lane and a 32-byte
//! tag, truncated to the 16 bytes AES-128-GCM takes. Implementing `d` and `i`
//! as well would add two code paths nothing calls — and the *point* of the id
//! variant is that it borrows the data-independent addressing of `i` for the
//! first half of the first pass and the data-dependent addressing of `d`
//! afterwards, so the two would not share much beyond the round function.
//!
//! # Shape
//!
//! The algorithm is a fixed-size block graph: memory is a matrix of 1 KiB
//! blocks (`lanes × lane_length`), and every block after the first two in each
//! lane is `G(previous_block, reference_block)` XORed with its own old value on
//! later passes. Two details are where implementations actually diverge, and
//! both are pinned by the RFC test vector below:
//!
//! * **Which block is referenced.** The reference index comes from the previous
//!   block's first word, mapped through the *reference area* — a window that
//!   excludes the current block and, on the first slice of the first pass,
//!   excludes everything after the start of the lane.
//! * **How the reference is chosen on the first half of the first pass.** There
//!   the indices come from a pseudo-random *address block* generated by running
//!   `G` twice over a counter block, rather than from memory. That is the
//!   side-channel-resistant half of the id variant.
//!
//! # Memory
//!
//! Memory is allocated as one `Vec` of blocks, so the cost is exactly the
//! configured `memory_kib` KiB. A hostile config asking for gigabytes gets an
//! allocation failure, not a partial computation; the caller's parameter
//! validation is the only thing standing between a profile field and that
//! allocation, which is why [`Argon2idParams::validate`] is public.

use crate::crypto::digest::Digest;
use crate::crypto::hash::Blake2b;
use alloc::vec::Vec;

/// Blocks in one lane-segment slice; fixed by the specification.
const SYNC_POINTS: usize = 4;
/// Words in one block (1024 bytes).
const BLOCK_WORDS: usize = 128;
/// Bytes in one block.
const BLOCK_BYTES: usize = BLOCK_WORDS * 8;
/// Address blocks cover this many indices each.
const ADDRESSES_IN_BLOCK: usize = 128;
/// The only version this implementation produces.
const ARGON2_VERSION: u32 = 0x13;
/// Variant tag written into `H0`: 2 = Argon2id.
const TYPE_ID: u32 = 2;

/// One 1 KiB Argon2 block, in little-endian 64-bit words.
type Block = [u64; BLOCK_WORDS];

/// Why a parameter set or an input was refused.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Argon2Error {
    /// `lanes` was zero or above the specification's limit.
    Lanes,
    /// Fewer than `8 * lanes` KiB of memory: the specification's floor, one
    /// block per slice per lane.
    MemoryTooSmall,
    /// `iterations` was zero.
    Iterations,
    /// The tag length was outside `4..=u32::MAX`.
    TagLength,
    /// The salt was shorter than the 8-byte minimum.
    Salt,
}

impl core::fmt::Display for Argon2Error {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Lanes => f.write_str("Argon2 lanes must be between 1 and 2^24-1"),
            Self::MemoryTooSmall => {
                f.write_str("Argon2 memory must be at least 8 KiB per lane (8 * lanes)")
            }
            Self::Iterations => f.write_str("Argon2 needs at least one iteration"),
            Self::TagLength => f.write_str("Argon2 tag length must be at least 4 bytes"),
            Self::Salt => f.write_str("Argon2 salt must be at least 8 bytes (RFC 9106 §3.1)"),
        }
    }
}

/// A validated Argon2id parameter set.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Argon2idParams {
    /// Memory cost in KiB.
    pub memory_kib: u32,
    /// Number of passes.
    pub iterations: u32,
    /// Degree of parallelism (independent lanes).
    pub lanes: u32,
    /// Output length in bytes.
    pub tag_len: u32,
}

impl Argon2idParams {
    /// Check the specification's bounds before anything is allocated.
    ///
    /// The memory floor is `8 * lanes` because a lane needs two pre-filled
    /// blocks plus room for four non-empty slices; below it the matrix cannot
    /// be built, and a library that silently rounds *up* would derive a key
    /// from a different memory cost than the config claims.
    pub fn validate(&self) -> Result<(), Argon2Error> {
        if self.lanes == 0 || self.lanes > 0x00ff_ffff {
            return Err(Argon2Error::Lanes);
        }
        if self.iterations == 0 {
            return Err(Argon2Error::Iterations);
        }
        if self.tag_len < 4 {
            return Err(Argon2Error::TagLength);
        }
        if self.memory_kib < 8 * self.lanes {
            return Err(Argon2Error::MemoryTooSmall);
        }
        Ok(())
    }

    /// Blocks after rounding the memory cost down to a multiple of
    /// `4 * lanes` (RFC 9106 §3.2).
    pub fn blocks(&self) -> usize {
        let per_lane = self.memory_kib / (SYNC_POINTS as u32 * self.lanes);
        (SYNC_POINTS as u32 * self.lanes * per_lane) as usize
    }
}

/// Derive `tag_len` bytes from `password` and `salt`.
///
/// `secret` and `associated_data` are the specification's optional keyed and
/// noted inputs; pass empty slices for the plain form (which is what Snell
/// uses — its "secret" is already folded into the password).
pub fn argon2id(
    password: &[u8],
    salt: &[u8],
    secret: &[u8],
    associated_data: &[u8],
    params: Argon2idParams,
) -> Result<Vec<u8>, Argon2Error> {
    params.validate()?;
    if salt.len() < 8 {
        return Err(Argon2Error::Salt);
    }

    let lanes = params.lanes as usize;
    let segment_length = params.blocks() / (lanes * SYNC_POINTS);
    let lane_length = segment_length * SYNC_POINTS;

    let h0 = initial_hash(password, salt, secret, associated_data, &params);

    // B[lane * lane_length + column]
    let mut memory: Vec<Block> = vec![[0u64; BLOCK_WORDS]; lanes * lane_length];

    // The first two blocks of every lane come straight from H0, which is what
    // makes the graph's roots unpredictable even though the shape is fixed.
    for lane in 0..lanes {
        for column in 0..2 {
            let mut seeded = Vec::with_capacity(h0.len() + 8);
            seeded.extend_from_slice(&h0);
            seeded.extend_from_slice(&(column as u32).to_le_bytes());
            seeded.extend_from_slice(&(lane as u32).to_le_bytes());
            memory[lane * lane_length + column] = block_from_hash(&seeded);
        }
    }

    for pass in 0..params.iterations as usize {
        for slice in 0..SYNC_POINTS {
            for lane in 0..lanes {
                fill_segment(
                    &mut memory,
                    lane,
                    lane_length,
                    segment_length,
                    pass,
                    slice,
                    params.iterations as usize,
                    lanes,
                );
            }
        }
    }

    // The tag is the XOR of every lane's last block.
    let mut final_block = memory[lane_length - 1];
    for lane in 1..lanes {
        let last = &memory[lane * lane_length + lane_length - 1];
        for (dst, src) in final_block.iter_mut().zip(last.iter()) {
            *dst ^= *src;
        }
    }
    let mut final_bytes = [0u8; BLOCK_BYTES];
    for (i, word) in final_block.iter().enumerate() {
        final_bytes[i * 8..(i + 1) * 8].copy_from_slice(&word.to_le_bytes());
    }

    Ok(variable_hash(&final_bytes, params.tag_len as usize))
}

/// `H0` — the 64-byte initial hash over every parameter and input, all lengths
/// little-endian 32-bit (RFC 9106 §3.2).
fn initial_hash(
    password: &[u8],
    salt: &[u8],
    secret: &[u8],
    associated_data: &[u8],
    params: &Argon2idParams,
) -> [u8; 64] {
    let mut hasher = Blake2b::new();
    for value in [
        params.lanes,
        params.tag_len,
        params.memory_kib,
        params.iterations,
        ARGON2_VERSION,
        TYPE_ID,
    ] {
        hasher.update(&value.to_le_bytes());
    }
    for field in [password, salt, secret, associated_data] {
        hasher.update(&(field.len() as u32).to_le_bytes());
        hasher.update(field);
    }
    let mut out = [0u8; 64];
    hasher.finalize_into(&mut out);
    out
}

/// `H'` — the variable-length hash (RFC 9106 §3.3).
///
/// For a 1024-byte block this is 30 chained 64-byte digests truncated to 32
/// bytes each, plus a final 64-byte digest. A plain "hash to 1024 bytes" does
/// not exist in BLAKE2, so the length is folded into the input instead, and the
/// chaining is what makes every output byte depend on all of the input.
fn variable_hash(input: &[u8], out_len: usize) -> Vec<u8> {
    let mut out = Vec::with_capacity(out_len);
    if out_len <= 64 {
        let mut hasher = Blake2b::with_params(out_len, &[]).expect("1..=64 is valid");
        hasher.update(&(out_len as u32).to_le_bytes());
        hasher.update(input);
        let mut buf = vec![0u8; out_len];
        hasher.finalize_into(&mut buf);
        return buf;
    }

    // r = ceil(out_len / 32) - 2 chained digests, then one final digest of
    // out_len - 32 * r bytes: 32 * r + (out_len - 32 * r) == out_len.
    let r = out_len.div_ceil(32) - 2;
    let mut hasher = Blake2b::new();
    hasher.update(&(out_len as u32).to_le_bytes());
    hasher.update(input);
    let mut chain = [0u8; 64];
    hasher.finalize_into(&mut chain);
    out.extend_from_slice(&chain[..32]);

    for _ in 1..r {
        let mut hasher = Blake2b::new();
        hasher.update(&chain);
        let mut next = [0u8; 64];
        hasher.finalize_into(&mut next);
        chain = next;
        out.extend_from_slice(&chain[..32]);
    }

    let tail_len = out_len - 32 * r;
    let mut hasher = Blake2b::with_params(tail_len, &[]).expect("1..=64 is valid");
    hasher.update(&chain);
    let mut tail = vec![0u8; tail_len];
    hasher.finalize_into(&mut tail);
    out.extend_from_slice(&tail);
    out
}

/// Turn a hash into a block by hashing it up to 1024 bytes.
fn block_from_hash(seed: &[u8]) -> Block {
    let bytes = variable_hash(seed, BLOCK_BYTES);
    let mut block = [0u64; BLOCK_WORDS];
    for (i, word) in block.iter_mut().enumerate() {
        let mut arr = [0u8; 8];
        arr.copy_from_slice(&bytes[i * 8..(i + 1) * 8]);
        *word = u64::from_le_bytes(arr);
    }
    block
}

/// The compression function `G` (RFC 9106 §3.5).
///
/// The permutation is applied to the eight 16-word rows first and then to the
/// eight 16-word columns, and the result is XORed with the row/column input —
/// the feed-forward is what stops `G` from being invertible.
fn compress(x: &Block, y: &Block) -> Block {
    let mut r = [0u64; BLOCK_WORDS];
    for i in 0..BLOCK_WORDS {
        r[i] = x[i] ^ y[i];
    }
    let mut q = r;

    for row in 0..8 {
        let mut v = [0u64; 16];
        v.copy_from_slice(&q[row * 16..row * 16 + 16]);
        permutation(&mut v);
        q[row * 16..row * 16 + 16].copy_from_slice(&v);
    }

    for column in 0..8 {
        let mut v = [0u64; 16];
        for row in 0..8 {
            v[2 * row] = q[row * 16 + 2 * column];
            v[2 * row + 1] = q[row * 16 + 2 * column + 1];
        }
        permutation(&mut v);
        for row in 0..8 {
            q[row * 16 + 2 * column] = v[2 * row];
            q[row * 16 + 2 * column + 1] = v[2 * row + 1];
        }
    }

    let mut out = [0u64; BLOCK_WORDS];
    for i in 0..BLOCK_WORDS {
        out[i] = q[i] ^ r[i];
    }
    out
}

/// `P` — the 16-word permutation, i.e. BLAKE2b's round with Argon2's `GB`.
///
/// Indices instead of four `&mut` references: the borrow checker cannot prove
/// four disjoint accesses into one array, and the workaround (splitting the
/// slice) would obscure the structure that the specification states as four
/// column indices and four diagonal ones.
fn permutation(v: &mut [u64; 16]) {
    gb(v, 0, 4, 8, 12);
    gb(v, 1, 5, 9, 13);
    gb(v, 2, 6, 10, 14);
    gb(v, 3, 7, 11, 15);
    gb(v, 0, 5, 10, 15);
    gb(v, 1, 6, 11, 12);
    gb(v, 2, 7, 8, 13);
    gb(v, 3, 4, 9, 14);
}

/// The `2 * trunc(a) * trunc(b)` term in `GB`.
///
/// Argon2's own tweak to BLAKE2's `G`: it multiplies the low 32 bits of both
/// addends, which is what makes the function's cost dominated by integer
/// multiplication rather than the XOR-and-rotate mix alone.
#[inline(always)]
fn mul_add_term(x: u64, y: u64) -> u64 {
    2u64.wrapping_mul((x & 0xffff_ffff).wrapping_mul(y & 0xffff_ffff))
}

/// `GB` (RFC 9106 §3.6), reading and writing four words of `v`.
#[inline(always)]
fn gb(v: &mut [u64; 16], i: usize, j: usize, k: usize, l: usize) {
    v[i] = v[i]
        .wrapping_add(v[j])
        .wrapping_add(mul_add_term(v[i], v[j]));
    v[l] = (v[l] ^ v[i]).rotate_right(32);
    v[k] = v[k]
        .wrapping_add(v[l])
        .wrapping_add(mul_add_term(v[k], v[l]));
    v[j] = (v[j] ^ v[k]).rotate_right(24);
    v[i] = v[i]
        .wrapping_add(v[j])
        .wrapping_add(mul_add_term(v[i], v[j]));
    v[l] = (v[l] ^ v[i]).rotate_right(16);
    v[k] = v[k]
        .wrapping_add(v[l])
        .wrapping_add(mul_add_term(v[k], v[l]));
    v[j] = (v[j] ^ v[k]).rotate_right(63);
}

/// Fill one segment (a pass's quarter of one lane).
///
/// Kept as one function because the three inputs that decide addressing —
/// `pass`, `slice` and whether the segment is in the first half of the first
/// pass — are only correct together; splitting it would invite a caller to pass
/// them inconsistently.
#[allow(clippy::too_many_arguments)]
fn fill_segment(
    memory: &mut [Block],
    lane: usize,
    lane_length: usize,
    segment_length: usize,
    pass: usize,
    slice: usize,
    total_passes: usize,
    lanes: usize,
) {
    // The first two blocks of the first slice already hold H0 output.
    let start_index = if pass == 0 && slice == 0 { 2 } else { 0 };
    // Argon2id's defining choice: the first half of the first pass uses
    // data-independent indices, everything after uses the previous block.
    let data_independent = pass == 0 && slice < 2;

    let mut address_block = [0u64; BLOCK_WORDS];
    let mut input_block = [0u64; BLOCK_WORDS];
    let zero_block = [0u64; BLOCK_WORDS];
    if data_independent {
        input_block[0] = pass as u64;
        input_block[1] = lane as u64;
        input_block[2] = slice as u64;
        input_block[3] = (lane_length * lanes) as u64;
        input_block[4] = total_passes as u64;
        input_block[5] = TYPE_ID as u64;
        if pass == 0 && slice == 0 {
            // This segment starts at index 2, so the in-loop rule
            // (`index % 128 == 0`) would never fire and the first 126 indices
            // would read a zeroed address block. The reference implementation
            // primes it here for exactly that reason.
            next_addresses(&mut address_block, &mut input_block, &zero_block);
        }
    }

    for index in start_index..segment_length {
        let current = lane * lane_length + slice * segment_length + index;
        // The previous block wraps to the end of the lane at the start of a
        // slice, which is what chains the slices into one lane.
        let previous = if index == 0 && slice == 0 {
            lane * lane_length + lane_length - 1
        } else {
            current - 1
        };

        let pseudo_rand = if data_independent {
            if index % ADDRESSES_IN_BLOCK == 0 {
                next_addresses(&mut address_block, &mut input_block, &zero_block);
            }
            address_block[index % ADDRESSES_IN_BLOCK]
        } else {
            memory[previous][0]
        };

        let mut reference_lane = ((pseudo_rand >> 32) as usize) % lanes;
        if pass == 0 && slice == 0 {
            // Nothing outside this lane exists yet, so the first slice can only
            // reference itself regardless of what the pseudo-random lane says.
            reference_lane = lane;
        }

        let reference_index = reference_index(
            pass,
            slice,
            index,
            segment_length,
            lane_length,
            pseudo_rand as u32,
            reference_lane == lane,
        );

        let new_block = compress(
            &memory[previous],
            &memory[reference_lane * lane_length + reference_index],
        );
        memory[current] = if pass == 0 {
            new_block
        } else {
            // Later passes XOR with the previous pass's value, which is what
            // makes the cost irreducible to a single pass.
            let mut out = new_block;
            for (dst, old) in out.iter_mut().zip(memory[current].iter()) {
                *dst ^= *old;
            }
            out
        };
    }
}

/// The address block for the next 128 indices: `G(zero, G(zero, counter))`.
fn next_addresses(address_block: &mut Block, input_block: &mut Block, zero_block: &Block) {
    input_block[6] += 1;
    let inner = compress(zero_block, input_block);
    *address_block = compress(zero_block, &inner);
}

/// Map a 32-bit pseudo-random value onto the reference block
/// (RFC 9106 §3.4.1.3).
///
/// The reference area is the set of blocks that may already exist and are not
/// the current one: the whole lane on later passes, the slices already filled
/// on earlier ones, and — inside the first slice of the first pass — only what
/// precedes the current index. Getting the area wrong does not corrupt the
/// output; it silently derives a *different* key, which is why this is the
/// function the RFC test vector exists to pin.
fn reference_index(
    pass: usize,
    slice: usize,
    index: usize,
    segment_length: usize,
    lane_length: usize,
    j1: u32,
    same_lane: bool,
) -> usize {
    let reference_area_size: u32 = if pass == 0 {
        if slice == 0 {
            (index - 1) as u32
        } else if same_lane {
            (slice * segment_length + index - 1) as u32
        } else {
            (slice * segment_length - usize::from(index == 0)) as u32
        }
    } else if same_lane {
        (lane_length - segment_length + index - 1) as u32
    } else {
        (lane_length - segment_length - usize::from(index == 0)) as u32
    };

    // `x = J1^2 / 2^32` then a proportional mapping, all in 64-bit so the
    // square cannot overflow, before subtracting to bias towards recent blocks.
    let relative = ((j1 as u64) * (j1 as u64)) >> 32;
    let relative = reference_area_size as u64 - 1 - ((reference_area_size as u64 * relative) >> 32);

    let start_position = if pass != 0 {
        if slice == SYNC_POINTS - 1 {
            0
        } else {
            (slice + 1) * segment_length
        }
    } else {
        0
    };

    (start_position + relative as usize) % lane_length
}

#[cfg(test)]
mod tests {
    use super::*;

    /// RFC 9106 §5.3: Argon2id, t=3, m=32, p=4, T=32, with the specification's
    /// fixed password / salt / secret / associated data.
    ///
    /// This is the only kind of test that can catch an addressing bug: every
    /// wrong variant of `reference_index` still produces 32 plausible-looking
    /// bytes, and only the expected tag distinguishes them.
    #[test]
    fn the_rfc_9106_argon2id_vector_matches() {
        let password = [0x01u8; 32];
        let salt = [0x02u8; 16];
        let secret = [0x03u8; 8];
        let associated_data = [0x04u8; 12];

        let tag = argon2id(
            &password,
            &salt,
            &secret,
            &associated_data,
            Argon2idParams {
                memory_kib: 32,
                iterations: 3,
                lanes: 4,
                tag_len: 32,
            },
        )
        .expect("RFC parameters are valid");

        assert_eq!(
            tag,
            vec![
                0x0d, 0x64, 0x0d, 0xf5, 0x8d, 0x78, 0x76, 0x6c, 0x08, 0xc0, 0x37, 0xa3, 0x4a, 0x8b,
                0x53, 0xc9, 0xd0, 0x1e, 0xf0, 0x45, 0x2d, 0x75, 0xb6, 0x5e, 0xb5, 0x25, 0x20, 0xe9,
                0x6b, 0x01, 0xe6, 0x59,
            ],
            "RFC 9106 §5.3 Argon2id tag"
        );
    }

    /// The parameter set Snell actually uses, checked for shape rather than
    /// against a published vector (there is none for it): three passes, 8 KiB,
    /// one lane, 32-byte tag truncated to 16 by the caller.
    #[test]
    fn the_snell_parameter_shape_is_accepted_and_deterministic() {
        let params = Argon2idParams {
            memory_kib: 8,
            iterations: 3,
            lanes: 1,
            tag_len: 32,
        };
        assert_eq!(params.validate(), Ok(()));
        // m' = 4 * lanes * floor(m / (4 * lanes)) = 8 blocks, 2 per slice.
        assert_eq!(params.blocks(), 8);

        let a = argon2id(b"psk", b"0123456789abcdef", &[], &[], params).unwrap();
        let b = argon2id(b"psk", b"0123456789abcdef", &[], &[], params).unwrap();
        assert_eq!(a, b, "the KDF is deterministic");
        assert_eq!(a.len(), 32);

        // Every input participates: a one-bit change in each moves the tag.
        let salt_changed = argon2id(b"psk", b"0123456789abcdeF", &[], &[], params).unwrap();
        assert_ne!(a, salt_changed);
        let psk_changed = argon2id(b"psK", b"0123456789abcdef", &[], &[], params).unwrap();
        assert_ne!(a, psk_changed);
        let secret_changed = argon2id(b"psk", b"0123456789abcdef", b"s", &[], params).unwrap();
        assert_ne!(a, secret_changed);
        let ad_changed = argon2id(b"psk", b"0123456789abcdef", &[], b"a", params).unwrap();
        assert_ne!(a, ad_changed);
    }

    #[test]
    fn the_tag_is_truncatable_to_aes_128_length_without_changing_its_prefix() {
        let params = Argon2idParams {
            memory_kib: 8,
            iterations: 3,
            lanes: 1,
            tag_len: 32,
        };
        let full = argon2id(b"psk", b"0123456789abcdef", &[], &[], params).unwrap();

        let short = Argon2idParams {
            tag_len: 16,
            ..params
        };
        let truncated = argon2id(b"psk", b"0123456789abcdef", &[], &[], short).unwrap();
        assert_eq!(truncated.len(), 16);
        // T is hashed into the output, so a different tag length is a different
        // computation — it is NOT a prefix of the longer tag. Snell therefore
        // has to derive 32 bytes and cut them, which is what it does.
        assert_ne!(truncated[..], full[..16]);
    }

    #[test]
    fn the_rfc_bounds_are_enforced_before_anything_is_allocated() {
        let ok = Argon2idParams {
            memory_kib: 8,
            iterations: 3,
            lanes: 1,
            tag_len: 32,
        };
        assert_eq!(ok.validate(), Ok(()));

        assert_eq!(
            Argon2idParams { lanes: 0, ..ok }.validate(),
            Err(Argon2Error::Lanes)
        );
        assert_eq!(
            Argon2idParams {
                iterations: 0,
                ..ok
            }
            .validate(),
            Err(Argon2Error::Iterations)
        );
        assert_eq!(
            Argon2idParams { tag_len: 3, ..ok }.validate(),
            Err(Argon2Error::TagLength)
        );
        // 8 KiB is exactly the floor for one lane, so anything below is out.
        assert_eq!(
            Argon2idParams {
                memory_kib: 7,
                ..ok
            }
            .validate(),
            Err(Argon2Error::MemoryTooSmall)
        );
        // The floor scales with lanes.
        assert_eq!(
            Argon2idParams {
                memory_kib: 32,
                lanes: 4,
                ..ok
            }
            .validate(),
            Ok(())
        );
        assert_eq!(
            Argon2idParams {
                memory_kib: 31,
                lanes: 4,
                ..ok
            }
            .validate(),
            Err(Argon2Error::MemoryTooSmall)
        );
    }

    #[test]
    fn a_short_salt_is_refused() {
        let params = Argon2idParams {
            memory_kib: 8,
            iterations: 3,
            lanes: 1,
            tag_len: 32,
        };
        assert_eq!(
            argon2id(b"p", b"short", &[], &[], params).map(|_| ()),
            Err(Argon2Error::Salt)
        );
    }

    #[test]
    fn the_variable_hash_consumes_exactly_the_requested_length() {
        for len in [4usize, 32, 64, 65, 96, 100, 1024] {
            assert_eq!(variable_hash(b"input", len).len(), len);
        }
        // Two calls agree, and the length is bound into the output.
        assert_eq!(variable_hash(b"x", 1024), variable_hash(b"x", 1024));
        assert_ne!(variable_hash(b"x", 1024), variable_hash(b"x", 1023));
        assert_ne!(variable_hash(b"x", 1024), variable_hash(b"y", 1024));
    }

    #[test]
    fn a_block_is_a_kibibyte_of_words() {
        let block = block_from_hash(b"seed");
        assert_eq!(block.len(), BLOCK_WORDS);
        assert_ne!(block, [0u64; BLOCK_WORDS]);
    }

    /// The compression function must not be a no-op in either of its two
    /// symmetric halves: a transposed row/column application would still be
    /// reproducible but wrong, so the asymmetry is checked directly.
    #[test]
    fn the_compression_function_mixes_rows_and_columns_differently() {
        let mut x = [0u64; BLOCK_WORDS];
        let mut y = [0u64; BLOCK_WORDS];
        for i in 0..BLOCK_WORDS {
            x[i] = i as u64;
            y[i] = 0x9e37_79b9_7f4a_7c15u64.wrapping_mul(i as u64 + 1);
        }
        let z = compress(&x, &y);
        assert_ne!(z, x);
        assert_ne!(z, y);
        // Every input word participates: flipping one changes the output.
        let mut x2 = x;
        x2[64] ^= 1;
        assert_ne!(compress(&x2, &y), z);
        let mut y2 = y;
        y2[3] ^= 1;
        assert_ne!(compress(&x, &y2), z);

        // G is symmetric in its operands — R = X ^ Y is, and the rest of the
        // function only ever sees R.
        assert_eq!(compress(&y, &x), z);

        // The degenerate case falls straight out of that: R is zero, so the
        // permutation has nothing to mix and the feed-forward contributes
        // nothing either. Worth pinning, because an implementation that used
        // X or Y directly instead of R would not produce it.
        assert_eq!(compress(&x, &x), [0u64; BLOCK_WORDS]);
    }
}
